---
  - name: "Finding old *.bak files for {{ connector }}."
    find:
      paths: "{{ connector_base }}/user/agent/"
      recurse: false
      use_regex: yes
      patterns: "^*.bak$"
      file_type: file
    register: files_to_delete

  - name: "Removing old *.bak files for {{ connector }}."
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"